### ISSUE TITLE
add validate function

### ISSUE THREAD

**Issue by mrzarquon** [adrienthebo/puppet-agent-bootstrap#1]
Being able to validate that $certname is signed and trusted correctly against the existing ssl private key, public key, and certificate in ssl/certs/$certname.pem would be another good option to have.

`puppet bootstrap validate`

returns 0 if:
can load certificate
can contact puppetserver (maybe?), to verify that the certificate it has signed can talk to the server in the puppet.conf?

without doing a full puppet run.

**Comment by adrienthebo** [comment]
Fixed in 4fd1ece5d044d9884edf9f36f9e8cb510c8782dd. Reopen if it's not handled as well as you'd like.
