### ISSUE TITLE
puppet bootstrap validate fails on Puppet 6

### ISSUE THREAD

**Issue by rharrison10** [adrienthebo/puppet-agent-bootstrap#16]
## Describe the Bug
The latest PRs merged into the master branch #13 #10 have the `purge` and `csr` commands working correctly with Puppet 6 but the `validate` command fails because it didn't download the CA or CRL from the Puppet Server.

```
# puppet bootstrap verify
Notice: Found a certificate for i-0e83examplea2ef8d
Notice: Private key matches certificate
Error: Failed to initialize SSL: The CA certificates are missing from '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
Error: Run `puppet agent -t`
Error: Connection to https://dev-puppetmaster-example.us-east-1.opsworks-cm.io:8140/puppet/v3 failed, trying next route: Request to https://dev-puppetmaster-example.us-east-1.opsworks-cm.io:8140/puppet/v3 failed after 0.0 seconds: The CA certificates are missing from '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
Wrapped exception:
The CA certificates are missing from '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
Error: Unable to reach Puppet master: No more routes to puppet
```

## Expected Behavior
The `validate` command downloads the necessary resources from the Puppet Server and successfully validates the certificate has been signed by the server and it is now safe to run the `puppet agent` command without errors.

## Steps to Reproduce
1. Configure `puppet.conf` and `csr_attributes.yaml` correctly to generate a CSR with the correct `certname`, `server`, and certificate extensions.
2. Install the puppet-agent-bootstrap module built from the master branch: `puppet module install /tmp/puppetlabs-bootstrap-0.2.2.tar.gz --ignore-dependencies`
3. Run `puppet bootstrap purge` to clean out any certificate activity or configuration before we were ready
4. Run `puppet bootstrap csr` to generate a new CSR with the correct `certname` and extensions.
5. Submit the CSR to the server and sign it.
6. Return the signed cert to the instance in the correct directory
7. Run `puppet bootstrap validate` to get the CA and CRL from the server to validate the certificate is correct and signed.

## Environment
 - Version puppet --version
6.21.1
 - Platform `Amazon Linux 2`

## Additional Context
These commands are run in the boot strap script included from the OpsWorks Puppet starter pack that we downloaded when we created the server.

**Comment by joshcooper** [comment]
@rharrison10 thanks for filing this issue. Puppet has builtin support for `purge` and `validate` using the `puppet ssl clean` and `puppet ssl verify` commands, respectively. We also recently added support for `puppet ssl generate_csr` which generates and saves the CSR locally without requiring network access. Since these are builtin I'm going to close this issue and this repo will be archived read-only.
